---
title: "Example web application with sales forecasting"
output: html_document
runtime: shiny
---

```{r, echo = FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(forecast)

# historical records from multiple stores
fsales <- "https://raw.githubusercontent.com/multidis/hult-inter-bus-reports-r/main/forecasting/sales_weekly.csv"
sales <- read_csv(fsales)

# latest (current) week
nweek_now <- max(sales$Week)
```

### Example UI inputs

```{r echo = FALSE}
inputPanel(
  selectInput("storenum", label = "Select store: ",
              choices = 1:max(sales$Store), selected = 1),
  sliderInput("horizon", label = "Forecast horizon (weeks): ",
              min = 2, max = 52, value = 8, step = 1)
)
```

### Example reactive chart

Please note all transformations responding to inputs must be included in **reactive* blocks, typically called `render...` (e.g. `renderPlot`, `renderTable` etc.).

```{r echo = FALSE}
renderPlot({
  horiz <- input$horizon
  
  sales_ts <- ts(sales %>% filter(Store == input$storenum) %>%
                   select(Weekly_Sales), frequency = 52)
  arima_model <- auto.arima(sales_ts, seasonal.test = "seas")
  arima_pred <- forecast(arima_model, h = horiz)
  
  sales_pred <- data.frame(Sales_Predicted = as.numeric(arima_pred$mean),
                           Week = (nweek_now + 1):(nweek_now + horiz))
  sales_pred %>% ggplot(aes(Week, Sales_Predicted)) +
    geom_line() + labs(x = "Weeks ahead", y = "Weekly Sales Forecast")
})
```
